name: Deploy web app

on:
  push:
    branches: [ "main" ]

env:
  AWS_S3_BUCKET: "melaniebrgr.com"
  AWS_S3_REGION: "eu-west-3"
  AWS_CLOUDFRONT_DISTRIBUTION_ID: "E2V9S2XI03EWOQ"

permissions:
  contents: read

jobs:
  build_and_deploy_job:
    permissions:
      contents: read # for actions/checkout to fetch code
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY }}
          aws-region: ${{ env.AWS_S3_REGION }}
      
      - name: Install Dependencies
        run: npm ci --production

      - name: Copy Files to S3
        working-directory: build/client/
        run: aws s3 sync ./ s3://${{ env.AWS_S3_BUCKET }} --delete

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ env.AWS_CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"

